''
'' Cerulean theme based off of the bootstrap theme of the same name
'' https://bootswatch.com/cerulean/
''
'' Author: Brett Schwarz
'' Copyright (c) 2019 by Brett Schwarz

!$THEME = "cerulean"

skinparam {
    EntityBackgroundColor #7acff5
    EntityBorderColor #000
    ParticipantBackgroundColor #7acff5
    ParticipantBorderColor #000
    ActorBackgroundColor #7acff5
    ActorBorderColor #000
    BoundaryBackgroundColor #7acff5
    BoundaryBorderColor #000
    DatabaseBackgroundColor #7acff5
    DatabaseBorderColor #000

    SequenceLifeLineBackgroundColor #7acff5
    SequenceLifeLineBorderColor #000

	BackgroundColor #00

    NoteBackgroundColor #f3e7f8
    NoteBorderColor #cc93e1
    NoteRoundCorner 20
    ArrowColor #000

    SequenceGroupBorderThickness 1
    Shadowing false
}